---

- name: Install cp4i
  hosts: localhost
  connection: local

- name: Install Operators
  ansible.builtin.import_playbook: operators/install-playbook.yaml

- name: Install Instances
  ansible.builtin.import_playbook: instances/install-playbook.yaml
  vars:
    ibm_entitlement_key: "{{ undef(hint='Provide an Entitled Registry key') }}"

