---
- hosts: localhost
  vars:
    config: "{{ lookup('file', '../config/config.json') }}"
    cp4i_ns: "{{ config | json_query('cp4i_namespace') }}"  
    ibm_entitlement_key: "{{ undef(hint='Provide an Entitled Registry key') }}"
    cp4i_config: "{{ config | json_query('instances.pn') }}"
  tasks:
    - name: Install local pre-requisites
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../common/prerequisites.yaml"

    - name: Include JSON config file
      include_vars:
        file: ../config/config.json
        name: config_from_json

    - name: get PN operator po
      kubernetes.core.k8s_info:
        validate_certs: false
        api_version: v1
        kind: Pod
        label_selectors:
          - "name=ibm-integration-platform-navigator-operator"
        namespace: openshift-operators
      register: pn_po 
      failed_when: false
    
    - name: Check status of PN 
      assert:
        that: pn_po.resources | length > 0
        fail_msg: "CP4I operator is not present"
        success_msg: "CP4I operator is present"

    - name: Create namespace for PN
      ansible.builtin.include_tasks: "{{ playbook_dir }}/setup-namespace.yaml"
      vars:
        namespace: "{{ cp4i_ns }}"

    - name: Print the variable value
      debug:
        msg: "The value of my_variable is: {{ config_from_json.instances.pn }}"

    - name: Render and display the template
      debug:
        msg: "{{ lookup('template', playbook_dir + '/templates/pn-cr.j2', namespace=config_from_json.instances.pn.namespace,config=config_from_json.instances.pn) }}"

    - name: PN - create CR
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', playbook_dir + '/templates/pn-cr.j2') }}"